repos:

  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-check
        stages: [pre-commit]
      

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [-tpy38, -q, --check]
        stages: [pre-commit]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
        stages: [pre-commit]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [pre-commit]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']