{# Jinja Template --> Sparql Query
 | Get any broader broader terms in a triple.
 | variables in template:
 |    - triple: triple to search from
#}

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc:   <http://purl.org/dc/terms/> 
SELECT ?bterm ?blbl WHERE {
  bind ( triple as ?term) 
  
  ?term skos:broader+ ?bterm.
  ?bterm skos:prefLabel ?blbl .
  filter(lang(?blbl)='en') 
} 