{# Jinja Template --> Sparql Query
 | Get the skos collection.
 | variables in template:
 |    - (optional) language: language of the collection

#}

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dc:   <http://purl.org/dc/terms/> 
SELECT ?collection ?title WHERE {
  ?collection rdf:type skos:Collection;
        dc:title ?title .
  {%if language%}FILTER(lang(?title) = {{language}}){%endif%}
}