name: Add reviewers based on mentioned issue
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  addReviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Get mentioned issue number
        id: getIssueNumber
        run: echo "::set-output name=issueNumber::$(jq --raw-output .pull_request.body issue.json | grep -oP '#\d+' | grep -oP '\d+')"

      - name: Get issue details
        id: getIssueDetails
        run: |
          issueNumber="${{ steps.getIssueNumber.outputs.issueNumber }}"
          issueDetails=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issueNumber}")
          echo "::set-output name=issueDetails::${issueDetails}"

      - name: Extract issuer from issue details
        id: extractIssuer
        run: |
          issueDetails="${{ steps.getIssueDetails.outputs.issueDetails }}"
          issuer=$(echo "${issueDetails}" | jq --raw-output .user.login)
          echo "::set-output name=issuer::${issuer}"

      - name: Add issuer as a reviewer
        id: addReviewer
        run: |
          issuer="${{ steps.extractIssuer.outputs.issuer }}"
          echo "Adding ${issuer} as a reviewer"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
            -d "{\"reviewers\": [\"${issuer}\"]}"